basePath: /
definitions:
  externalservice.Item:
    type: object
  http.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  http.OkResponse:
    properties:
      ok:
        type: boolean
    type: object
  http.ProcessBatchItemsRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/externalservice.Item'
        type: array
    type: object
info:
  contact: {}
  description: This API represents interface for sending items to processing
  title: Items processing API
  version: "1.0"
paths:
  /items/batch:
    post:
      consumes:
      - application/json
      description: Send items for processing
      parameters:
      - description: Request object
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/http.ProcessBatchItemsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/http.OkResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Process batch of items
      tags:
      - Item
swagger: "2.0"
